// angular-sample-spa/src/app/app.component.ts
import { Component } from '@angular/core';
import AppID from 'ibmcloud-appid-js';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  userName = '';
  errorMessage = '';
  buttonStyle = 'show';
  messageStyle = 'hide';
  errorStyle = 'hide';
  async onLoginClick() {
    const appID = new AppID();
    try {
      await appID.init({
        clientId: '<SPA_CLIENT_ID>',
        discoveryEndpoint: '<WELL_KNOWN_ENDPOINT>'
      });
      const tokens = await appID.signin();
      const decodeIDTokens = tokens.idTokenPayload;
      this.userName = decodeIDTokens.name;
      this.buttonStyle = 'hide';
      this.messageStyle = 'show';
      this.errorStyle = 'hide';
    } catch (e) {
      this.errorStyle = 'show';
      this.errorMessage = e.message;
    }
  }
}

<style>
  .hide {
    display: none;
  }
  .show {
    display: block;
  }
</style>

<button
  [ngClass]="buttonStyle"
  style="background-color: #4178BE; width: 270px;
	height: 40px;color: #FFFFFF;font-size: 14px;border: none; margin-left: 10px;"
  id="login"
  (click)="onLoginClick()">Login with IBM Cloud App ID
</button>
<p [ngClass]="messageStyle" style="margin-left: 10px;" id="welcomeNameID">Hi {{userName}}! You are now authenticated </p>
<div [ngClass]="errorStyle" id="error" style="margin-left: 10px; color: red;">{{errorMessage}}</div>

// react-sample-app/src/App.js
import React from 'react';
import logo from './logo.svg';
import './App.css';
import AppID from 'ibmcloud-appid-js';

function App() {

  const appID = React.useMemo(() => {
    return new AppID()
  }, []);

  const [errorState, setErrorState] = React.useState(false);
  const [errorMessage, setErrorMessage] = React.useState('');

  (async () => {
    try {
      await appID.init({
        clientId: '<SPA_CLIENT_ID>',
        discoveryEndpoint: '<WELL_KNOWN_ENDPOINT>'
      });
    } catch (e) {
      setErrorState(true);
      setErrorMessage(e.message);
    }
  })();

  const [welcomeDisplayState, setWelcomeDisplayState] = React.useState(false);
  const [loginButtonDisplayState, setLoginButtonDisplayState] = React.useState(true);
  const [userName, setUserName] = React.useState('');

  const loginAction = async () => {
    try {
      const tokens = await appID.signin();
      setErrorState(false);
      setLoginButtonDisplayState(false);
      setWelcomeDisplayState(true);
      setUserName(tokens.idTokenPayload.name);
    } catch (e) {
      setErrorState(true);
      setErrorMessage(e.message);
    }
  };

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        {welcomeDisplayState && <div> Welcome {userName}! You are now authenticated.</div>}
        {loginButtonDisplayState &&
        <button
            style={{fontSize: '24px', backgroundColor: 'skyblue', border: 'none'}}
            id='login'
            onClick={loginAction}>Login
        </button>
        }
        {errorState && <div style={{color: 'red'}}>{errorMessage}</div>}
      </header>
    </div>
  );
}

export default App;
