// angular-sample-spa/src/app/welcome/welcome.component.ts
import { Component, Output, EventEmitter, OnInit } from '@angular/core';
import AppID from 'ibmcloud-appid-js';

@Component({
  selector: 'app-welcome',
  templateUrl: './welcome.component.html',
  styleUrls: ['./welcome.component.css']
})

export class WelcomeComponent implements OnInit {
  style = 'show';
  spinner = 'hide';
  buttonDisplay = 'show';
  errorStyle = 'hide';
  errorMessage = '';
  appid = new AppID();
  @Output() changeState = new EventEmitter();
  async ngOnInit() {
    try {
      await this.appid.init({
        clientId: '<CLIENT_ID>',
        discoveryEndpoint: '<WELL_KNOWN_ENDPOINT>'
      });
    } catch (e) {
      this.errorMessage = e.message;
      this.errorStyle = 'show';
    }
  }
  async onLoginClick() {
    try {
      this.buttonDisplay = 'hide';
      this.spinner = 'show';
      const tokens = await this.appid.signin();
      const userInfo =  await this.appid.getUserInfo(tokens.accessToken);
      const decodeIDTokens = tokens.idTokenPayload;
      const userName = 'Hi ' + decodeIDTokens.name + ', Congratulations!';
      const idToken = JSON.stringify(decodeIDTokens);
      const userData = JSON.stringify(userInfo);
      this.style = 'hide';
      this.changeState.emit({userName, idToken, userData});
    } catch (e) {
      this.errorMessage = e.message;
      this.spinner = 'hide';
      this.errorStyle = 'show';
      this.buttonDisplay = 'show';

    }
  }
}

<div id="welcome" [ngClass]="style">
  <div class="welcome-display">
    <div>
      <img alt="App ID Logo" class="logo-icon" src="../../assets/images/app_id_icon.svg">
        <p>
          Welcome to the<br>
          IBM Cloud App ID SPA SDK<br>
          Sample App
        </p>
    </div>
    <div [ngClass]="spinner" class="loader"></div>
    <button id="login" [ngClass]='buttonDisplay' (click)="onLoginClick()">Login</button>
    <div [ngClass]="errorStyle" id="error">{{errorMessage}}</div>
  </div>
  <div class="hintSection">
    <div class="flex-bottom"><img alt="hint image" id="hintIcon" src="../../assets/images/hint_icon.svg"></div>
    <div class="flex-bottom">
      Hint: To get started, click<br>
      the Login button above to reveal<br>
      the App ID login Pop-up window.
    </div>
  </div>
</div>

// react-sample-app/src/Welcome.js
import React, {useMemo, useState} from 'react';
import logo from './images/app_id_icon.svg';
import hint from './images/hint_icon.svg';
import AppID from 'ibmcloud-appid-js';

export default function Welcome() {
    const [userName, setUserName] = useState('');
    const [idToken, setIdToken] = useState('');
    const [userInfo, setUserInfo] = useState('');
    const [errorState, setErrorState] = useState('hide')
    const [errorMessage, setErrorMessage] = useState('Error');
    const [displayState, setDisplayState] = useState('show');
    const [welcomeDisplayState, setWelcomeDisplayState] = useState('hide');

    const appid = useMemo(() => {
        return new AppID()
    }, []);

    (async () => {
        try {
            await appid.init({
                "clientId": "<CLIENT_ID>",
                "discoveryEndpoint": "<WELL_KNOWN_ENDPOINT>"
            });
        } catch (e) {
            setErrorState('error')
            setErrorMessage(e.message);
        }
    })();

    const loginAction = async () => {
        try {
            const tokens = await appid.signin();
            const userInformation =  await appid.getUserInfo(tokens.accessToken);
            const decodeToken = tokens.idTokenPayload;
            setUserName(decodeToken.name);
            setIdToken(JSON.stringify(decodeToken));
            setUserInfo(JSON.stringify(userInformation));
            setDisplayState('hide');
            setWelcomeDisplayState('show');
        } catch (e) {
            setErrorState('error')
            setErrorMessage(e.message);
        }
    };
    return (
        <>
            <div className="wrapper">
                <span><b>IBM Cloud AppID SDK Sample SPA</b></span>
            </div>
            <div className={displayState}>
                <div className='welcome-display'>
                    <img alt="App ID Logo" className="logo-icon" src={logo} />
                    <p>
                        Welcome to the<br/>
                        IBM Cloud App ID SPA SDK<br/>
                        Sample App
                    </p>
                    <button id="login" onClick={loginAction} >Login</button>
                    <div className={errorState}>{errorMessage}</div>
                </div>
                <div className="hintSection">
                    <div className="flex-bottom">
                        <img alt="hint icon" id="hintIcon" src={hint} />
                    </div>
                    <div className="flex-bottom">
                        Hint: To get started, click<br/>
                        the Login button above to reveal<br/>
                        the App ID login Pop-up window.
                    </div>
                </div>
            </div>
            <div className={welcomeDisplayState}>
                <div className="welcome-display">
                    <p id="welcomeNameID">Hi {userName}, Congratulations!</p>
                    <p id="welcomeMessageII">You've made your first authentication.</p>
                </div>
                <div className="token-display">
                    <h4>ID Token</h4>
                    <hr/>
                    <p>{idToken}</p>
                </div>
                <div className="info-display">
                    <h4>User Information</h4>
                    <hr/>
                    <p>{userInfo}</p>
                </div>
            </div>
        </>
    );
}
